name: Run BDD Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      ENV: "QA"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run BDD tests
      id: bdd-tests
      run: npm run test:bdd || npm run test:rerun

    # - name: Install Artillery
    #   run: npm install -g artillery@2.0.30

    - name: Upload test artifacts
      if: ${{(success() || failure()) && env.ENV == 'QA'}}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/cucumber-report.html
          test-results/cucumber-report.json
        retention-days: 30

    - name: Warm up Endpoints
      continue-on-error: true
      uses: artilleryio/action-cli@v2
      with:
        command: run  artillery/test.yml 

    - name: Parse results and notify Teams
      if: success() || failure()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: "https://afgtest.webhook.office.com/webhookb2/526935bf-3267-4f9e-a896-31a73dac597e@f7a3baa7-fae3-415b-b481-a71ed92d3103/IncomingWebhook/cfae1b3a8ab24238b7a9c5e95eb1b560/fddd096f-a6ac-4669-a86e-83a4d17b38a4/V2M-or91x-1APxfGbwSCuCecVYAcm7pgIDj1Tsh6jJPAw1"
        ENV_NAME: ${{ env.ENV }}
        BRANCH: ${{ github.ref_name }}
        ACTOR: ${{ github.actor }}
        SHA: ${{ github.sha }}
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
      run: npx ts-node .github/scripts/parse-results.ts

   

  #X ray Integration code commented out for now
    #- name: Submit results to Xray
     # if: success() || failure() && env.ENV == 'QA'
     # uses: mikepenz/xray-action@v2.4.5
     # with:
     #   username: ${{ secrets.client_id }}
      #  password: ${{ secrets.client_secret }}
      #  testFormat: "cucumber"
      #  testPaths: "test-results/cucumber-report.json"
        #testExecKey: "QA-4219"
        #testPlanKey: "QA-4222"
        #projectKey: "QA"
       # testExecutionJson: "bdd/helper/testExecution.json"
    
    # - name: Get Authentication Token
    #   id: get-token
    #   run: | 
    #     response=$(curl -s -X POST -H "Content-Type: application/json" \
    #     -d '{"client_id": "'"$XRAY_CLIENT_ID"'", "client_secret": "'"$XRAY_CLIENT_SECRET"'"}' \
    #     https://xray.cloud.getxray.app/api/v2/authenticate) 
    #     token=$(echo $response | tr -d '"')
    #     echo "Generated Token: $token" # This line will echo the token
    #     echo "XRAY_TOKEN=$token" >> $GITHUB_ENV
        
    #   env: 
    #     XRAY_CLIENT_ID: ${{ secrets.client_id }} 
    #     XRAY_CLIENT_SECRET: ${{ secrets.client_secret }}

    # - name: Submit Results to Xray 
    #   run: | 
    #    curl -H "Content-Type: multipart/form-data" -X POST -F info=@bdd/testExecution.json -F results=@test-results/cucumber-report.json -H "Authorization: Bearer $XRAY_TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
